version: '3.8'

services:

  myapi-frontend:
    container_name: myapi-frontend-dev
    image: myapi-frontend:dev
    ports:
      - "3001:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
  keycloak:
    container_name: keycloack-dev
    image: quay.io/keycloak/keycloak:17.0.0
    ports:
      - "8080:8080"
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    command:
      - start-dev

